In [80]:
import pandas as pd
data=pd.read_excel("data1.xlsx")

In [81]:
df=pd.DataFrame(data)
df

             Date     Close      Open      High       Low
0    Nov 26, 2021  36157.80  37055.25  37093.75  36025.05
1    Nov 25, 2021  37364.75  37324.00  37538.70  37115.00
2    Nov 24, 2021  37465.00  37401.00  37895.50  37239.45
3    Nov 23, 2021  37284.30  36921.65  37474.95  36682.00
4    Nov 22, 2021  37182.10  38199.90  38214.10  36680.05
..            ...       ...       ...       ...       ...
511  Nov 07, 2019  30664.35  30801.00  30848.95  30463.00
512  Nov 06, 2019  30682.60  30260.30  30780.00  30052.00
513  Nov 05, 2019  30294.15  30420.05  30519.90  30155.10
514  Nov 04, 2019  30396.05  30457.95  30658.00  30267.00
515  Nov 01, 2019  30374.10  30200.05  30449.45  30063.10

[516 rows x 5 columns]

In [82]:
Net_change=[]
Net_Pecent_Change=[]
Dates=[]
for i in range(len(df)-1,0,-5):
    net_change=df.loc[i,'Close']-df.loc[i-1,'Open']
    Net_change.append(net_change)
    net_percent_change=((df.loc[i-1,'Open']-df.loc[i,'Close'])/df.loc[i,'Close'])*100
    Net_Pecent_Change.append("%.2f"%net_percent_change)
    Dates.append(df.loc[i,'Date']+"-"+df.loc[i-1,'Date'])
    print("\nNet_Change & Net_%_Change between dates "+df.loc[i,'Date']+"-"+df.loc[i-1,'Date']+" is %.2f %.2f"%(net_change,net_percent_change))

Net_Change & Net_%_Change between dates Nov 01, 2019-Nov 04, 2019 is -83.85 0.28

Net_Change & Net_%_Change between dates Nov 08, 2019-Nov 11, 2019 is 59.00 -0.19

Net_Change & Net_%_Change between dates Nov 18, 2019-Nov 19, 2019 is -42.10 0.14

Net_Change & Net_%_Change between dates Nov 25, 2019-Nov 26, 2019 is -51.85 0.16

Net_Change & Net_%_Change between dates Dec 02, 2019-Dec 03, 2019 is -28.55 0.09

Net_Change & Net_%_Change between dates Dec 09, 2019-Dec 10, 2019 is -42.45 0.14

Net_Change & Net_%_Change between dates Dec 16, 2019-Dec 17, 2019 is -89.80 0.28

Net_Change & Net_%_Change between dates Dec 23, 2019-Dec 24, 2019 is 24.45 -0.08

Net_Change & Net_%_Change between dates Dec 31, 2019-Jan 01, 2020 is -51.25 0.16

Net_Change & Net_%_Change between dates Jan 07, 2020-Jan 08, 2020 is 307.80 -0.98

Net_Change & Net_%_Change between dates Jan 14, 2020-Jan 15, 2020 is 80.05 -0.25

Net_Change & Net_%_Change between dates Jan 21, 2020-Jan 22, 2020 is -107.20 0.35

Net_Change & Net_%_Change between dates Jan 28, 2020-Jan 29, 2020 is -188.40 0.61

Net_Change & Net_%_Change between dates Feb 03, 2020-Feb 04, 2020 is -267.85 0.89

Net_Change & Net_%_Change between dates Feb 10, 2020-Feb 11, 2020 is -161.65 0.52

Net_Change & Net_%_Change between dates Feb 17, 2020-Feb 18, 2020 is 120.50 -0.39

Net_Change & Net_%_Change between dates Feb 25, 2020-Feb 26, 2020 is 237.90 -0.78

Net_Change & Net_%_Change between dates Mar 03, 2020-Mar 04, 2020 is 108.75 -0.37

Net_Change & Net_%_Change between dates Mar 11, 2020-Mar 12, 2020 is 1300.40 -4.91

Net_Change & Net_%_Change between dates Mar 18, 2020-Mar 19, 2020 is 1018.95 -4.97

Net_Change & Net_%_Change between dates Mar 25, 2020-Mar 26, 2020 is -213.00 1.15

Net_Change & Net_%_Change between dates Apr 01, 2020-Apr 03, 2020 is -54.90 0.30

Net_Change & Net_%_Change between dates Apr 13, 2020-Apr 15, 2020 is -501.90 2.58

Net_Change & Net_%_Change between dates Apr 21, 2020-Apr 22, 2020 is 93.85 -0.49

Net_Change & Net_%_Change between dates Apr 28, 2020-Apr 29, 2020 is 136.05 -0.66

Net_Change & Net_%_Change between dates May 06, 2020-May 07, 2020 is 201.95 -1.03

Net_Change & Net_%_Change between dates May 13, 2020-May 14, 2020 is 391.35 -1.99

Net_Change & Net_%_Change between dates May 20, 2020-May 21, 2020 is -86.65 0.49

Net_Change & Net_%_Change between dates May 28, 2020-May 29, 2020 is 251.80 -1.31

Net_Change & Net_%_Change between dates Jun 04, 2020-Jun 05, 2020 is -51.05 0.25

Net_Change & Net_%_Change between dates Jun 11, 2020-Jun 12, 2020 is 953.85 -4.65

Net_Change & Net_%_Change between dates Jun 18, 2020-Jun 19, 2020 is 22.65 -0.11

Net_Change & Net_%_Change between dates Jun 25, 2020-Jun 26, 2020 is -93.80 0.44

Net_Change & Net_%_Change between dates Jul 02, 2020-Jul 03, 2020 is -171.70 0.78

Net_Change & Net_%_Change between dates Jul 09, 2020-Jul 10, 2020 is 152.45 -0.67

Net_Change & Net_%_Change between dates Jul 16, 2020-Jul 17, 2020 is 111.85 -0.52

Net_Change & Net_%_Change between dates Jul 23, 2020-Jul 24, 2020 is 245.25 -1.06

Net_Change & Net_%_Change between dates Jul 30, 2020-Jul 31, 2020 is -1.00 0.00

Net_Change & Net_%_Change between dates Aug 06, 2020-Aug 07, 2020 is 41.95 -0.19

Net_Change & Net_%_Change between dates Aug 13, 2020-Aug 14, 2020 is -110.60 0.50

Net_Change & Net_%_Change between dates Aug 20, 2020-Aug 21, 2020 is -191.30 0.87

Net_Change & Net_%_Change between dates Aug 27, 2020-Aug 28, 2020 is -79.55 0.34

Net_Change & Net_%_Change between dates Sep 03, 2020-Sep 04, 2020 is 247.20 -1.05

Net_Change & Net_%_Change between dates Sep 10, 2020-Sep 11, 2020 is 56.05 -0.25

Net_Change & Net_%_Change between dates Sep 17, 2020-Sep 18, 2020 is 0.60 -0.00

Net_Change & Net_%_Change between dates Sep 24, 2020-Sep 25, 2020 is -253.15 1.24

Net_Change & Net_%_Change between dates Oct 01, 2020-Oct 05, 2020 is -3.50 0.02

Net_Change & Net_%_Change between dates Oct 09, 2020-Oct 12, 2020 is -32.25 0.13

Net_Change & Net_%_Change between dates Oct 16, 2020-Oct 19, 2020 is -310.70 1.32

Net_Change & Net_%_Change between dates Oct 23, 2020-Oct 26, 2020 is 17.05 -0.07

Net_Change & Net_%_Change between dates Oct 30, 2020-Nov 02, 2020 is -320.65 1.34

Net_Change & Net_%_Change between dates Nov 06, 2020-Nov 09, 2020 is -300.80 1.12

Net_Change & Net_%_Change between dates Nov 13, 2020-Nov 14, 2020 is -148.25 0.52

Net_Change & Net_%_Change between dates Nov 20, 2020-Nov 23, 2020 is -185.10 0.63

Net_Change & Net_%_Change between dates Nov 27, 2020-Dec 01, 2020 is -117.95 0.40

Net_Change & Net_%_Change between dates Dec 07, 2020-Dec 08, 2020 is -49.40 0.16

Net_Change & Net_%_Change between dates Dec 14, 2020-Dec 15, 2020 is 88.40 -0.29

Net_Change & Net_%_Change between dates Dec 21, 2020-Dec 22, 2020 is -97.05 0.33

Net_Change & Net_%_Change between dates Dec 29, 2020-Dec 30, 2020 is -128.90 0.41

Net_Change & Net_%_Change between dates Jan 05, 2021-Jan 06, 2021 is -76.25 0.24

Net_Change & Net_%_Change between dates Jan 12, 2021-Jan 13, 2021 is -147.95 0.46

Net_Change & Net_%_Change between dates Jan 19, 2021-Jan 20, 2021 is 94.65 -0.29

Net_Change & Net_%_Change between dates Jan 27, 2021-Jan 28, 2021 is 442.25 -1.46

Net_Change & Net_%_Change between dates Feb 03, 2021-Feb 04, 2021 is 290.70 -0.83

Net_Change & Net_%_Change between dates Feb 10, 2021-Feb 11, 2021 is 125.40 -0.35

Net_Change & Net_%_Change between dates Feb 17, 2021-Feb 18, 2021 is -99.00 0.27

Net_Change & Net_%_Change between dates Feb 24, 2021-Feb 25, 2021 is -33.30 0.09

Net_Change & Net_%_Change between dates Mar 03, 2021-Mar 04, 2021 is 765.50 -2.10

Net_Change & Net_%_Change between dates Mar 10, 2021-Mar 12, 2021 is -497.50 1.38

Net_Change & Net_%_Change between dates Mar 18, 2021-Mar 19, 2021 is 287.95 -0.85

Net_Change & Net_%_Change between dates Mar 25, 2021-Mar 26, 2021 is -743.55 2.25

Net_Change & Net_%_Change between dates Apr 05, 2021-Apr 06, 2021 is -203.85 0.62

Net_Change & Net_%_Change between dates Apr 12, 2021-Apr 13, 2021 is -132.80 0.43

Net_Change & Net_%_Change between dates Apr 20, 2021-Apr 22, 2021 is 322.00 -1.03

Net_Change & Net_%_Change between dates Apr 28, 2021-Apr 29, 2021 is -206.05 0.61

Net_Change & Net_%_Change between dates May 05, 2021-May 06, 2021 is -134.20 0.41

Net_Change & Net_%_Change between dates May 12, 2021-May 14, 2021 is 20.25 -0.06

Net_Change & Net_%_Change between dates May 20, 2021-May 21, 2021 is -154.45 0.46

Net_Change & Net_%_Change between dates May 27, 2021-May 28, 2021 is -403.95 1.15

Net_Change & Net_%_Change between dates Jun 03, 2021-Jun 04, 2021 is 11.95 -0.03

Net_Change & Net_%_Change between dates Jun 10, 2021-Jun 11, 2021 is -153.65 0.44

Net_Change & Net_%_Change between dates Jun 17, 2021-Jun 18, 2021 is -117.80 0.34

Net_Change & Net_%_Change between dates Jun 24, 2021-Jun 25, 2021 is -223.15 0.64

Net_Change & Net_%_Change between dates Jul 01, 2021-Jul 02, 2021 is -80.95 0.23

Net_Change & Net_%_Change between dates Jul 08, 2021-Jul 09, 2021 is 84.70 -0.24

Net_Change & Net_%_Change between dates Jul 15, 2021-Jul 16, 2021 is -61.65 0.17

Net_Change & Net_%_Change between dates Jul 23, 2021-Jul 26, 2021 is 151.90 -0.43

Net_Change & Net_%_Change between dates Jul 30, 2021-Aug 02, 2021 is -147.35 0.42

Net_Change & Net_%_Change between dates Aug 06, 2021-Aug 09, 2021 is 41.05 -0.11

Net_Change & Net_%_Change between dates Aug 13, 2021-Aug 16, 2021 is 60.65 -0.17

Net_Change & Net_%_Change between dates Aug 23, 2021-Aug 24, 2021 is 7.10 -0.02

Net_Change & Net_%_Change between dates Aug 30, 2021-Aug 31, 2021 is -19.15 0.05

Net_Change & Net_%_Change between dates Sep 06, 2021-Sep 07, 2021 is 57.10 -0.16

Net_Change & Net_%_Change between dates Sep 14, 2021-Sep 15, 2021 is -46.65 0.13

Net_Change & Net_%_Change between dates Sep 21, 2021-Sep 22, 2021 is 21.50 -0.06

Net_Change & Net_%_Change between dates Sep 28, 2021-Sep 29, 2021 is 368.50 -0.97

Net_Change & Net_%_Change between dates Oct 05, 2021-Oct 06, 2021 is -23.65 0.06

Net_Change & Net_%_Change between dates Oct 12, 2021-Oct 13, 2021 is -161.70 0.42

Net_Change & Net_%_Change between dates Oct 20, 2021-Oct 21, 2021 is -78.10 0.20

Net_Change & Net_%_Change between dates Oct 27, 2021-Oct 28, 2021 is 82.95 -0.20

Net_Change & Net_%_Change between dates Nov 03, 2021-Nov 04, 2021 is -103.95 0.26

Net_Change & Net_%_Change between dates Nov 11, 2021-Nov 12, 2021 is 515.05 -1.33

Net_Change & Net_%_Change between dates Nov 18, 2021-Nov 22, 2021 is -94.20 0.25

In [83]:
print("Representation In Tabular Format")
new_df=pd.DataFrame(list(zip(Dates,Net_change,Net_Pecent_Change)),columns=['Between Dates','Net_Change','Net_%_Change'])
new_df

Representation In Tabular Format

                 Between Dates  Net_Change Net_%_Change
0    Nov 01, 2019-Nov 04, 2019      -83.85         0.28
1    Nov 08, 2019-Nov 11, 2019       59.00        -0.19
2    Nov 18, 2019-Nov 19, 2019      -42.10         0.14
3    Nov 25, 2019-Nov 26, 2019      -51.85         0.16
4    Dec 02, 2019-Dec 03, 2019      -28.55         0.09
..                         ...         ...          ...
98   Oct 20, 2021-Oct 21, 2021      -78.10         0.20
99   Oct 27, 2021-Oct 28, 2021       82.95        -0.20
100  Nov 03, 2021-Nov 04, 2021     -103.95         0.26
101  Nov 11, 2021-Nov 12, 2021      515.05        -1.33
102  Nov 18, 2021-Nov 22, 2021      -94.20         0.25

[103 rows x 3 columns]